version: '3'

services:
  app:
    build: .
    ports:
      - "9000:80"
    volumes:
      - "./:/usr/share/nginx"
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - network

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: senhabraba
    networks:
      - network

networks:
  network:
    driver: bridge
